### ISSUE TITLE
Setup README

### ISSUE THREAD

**Issue by thymikee** [graphql-community/graphql-directive-uid#1]

**Comment by thymikee** [comment]
You can refer to https://twitter.com/kentcdodds/status/976813153647394816 :)

**Comment by czystyl** [comment]
@thymikee what you think about the logo: https://www.emojione.com/emoji/1f43f We can add something for the smile like on the @kentcdodds :)
And this one https://github.com/kentcdodds/all-contributors#emoji-key

This is overkill for that small repository, but it could be great to have a nice setup for all directives what you think?
