### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by thymikee** [graphql-community/graphql-directive-uid#12]
@czystyl can you take care of that? 🙂

**Comment by czystyl** [comment]
Sure! :) 

#11 is related to this issues, how do we want to name our packages?

**Comment by thymikee** [comment]
I'd go with `graphql-directive-uid` or `@graphql-community/directive-uid` if we had an organization scope. @evans what do you think?

**Comment by thymikee** [comment]
Let's go with `graphql-directive-uid` for now :)

**Comment by czystyl** [comment]
done 👍 Want automatically publishing new versions?

**Comment by zamotany** [comment]
Don't forget to bump version in `package.json`

**Comment by thymikee** [comment]
@czystyl FWIW, running `yarn publish` will do that for you and will create a tag btw

**Comment by jukben** [comment]
[OT] @czystyl and I prefer https://github.com/sindresorhus/np 💃

**Comment by jukben** [comment]
Also, If I'm correct there is introduced some auto-deploying by @zamotany, right? All we have to do is set ENV token and tag some commit on the master branch, it should trigger CircleCI and deploy to NPM?

**Comment by jukben** [comment]
@czystyl we can close this, right?
